### ISSUE TITLE
Cannot create a RasterLayer object from this file. (file does not exist)

### ISSUE THREAD

**Issue by jdilger** [openforis/sepal_mspa#1]
Hey there,

When running this in Sepal I get the following error: "Cannot create a RasterLayer object from this file. (file does not exist)" The file really does exist, and is a tiff as byte (I tested int16 as well).  Mspa does work in sepal using the test data.

I ran mspa locally using my image which is not found and it works perfectly, which leads me to believe there is an issue in Sepal.  At a glance the permissions seem to be the same as the test.tif. 

-John

**Comment by lecrabe** [comment]
Dear John
You are probably using the default instance which would be too small for your image (is has only 2 GB of RAM, easy to overflow).
If you start a stronger instance you shouldn't run into the problem. 
But I agree that there should be a nicer warning that the error it shows, the module needs some update anyway.

**Comment by jdilger** [comment]
I am testing with a comparably small image  (101kB for mine, and 69kB for the example image). I tried  it again with a m2 and m4 instance but the results were the same.  It been a while since I've needed to use Sepal, is there another step I am missing in connecting the instance to the app? Both of those should have more than enough RAM.

**Comment by lecrabe** [comment]
Dear John
Coming back to you on this, can you clarify what module you are using in SEPAL ? Can you confirm you use the Fragmentation Tool ?
I have tried a couple of datasets and they seem to work, so difficult to reproduce your error without the data. Can you tell me exactly what is the name of your file ? You wrote "tiff" so maybe that is where the problem is, it is looking for ".tif" extensions.

**Comment by jdilger** [comment]
Hey lecrabe,
Yes I am using the Fragmentation Tool, and with a '.tif'.  
I was able to get it working by deleting initial folders that it creates when running the tool... I cannot replicate the error now though as well, so I am not sure what the issue was. I tested running it again using the default instance, with float, int64, and byte and they all worked.
